config/routes.rb
Olapp::Application.routes.draw do

  # get "users/new"

    resources :users do
        member do
            get :following, :followers
        end
        resources :trips, only: [:index, :create, :destroy]  ## if we remove this, the home page does not work
        resources :enrollments, only: [:index, :create, :destroy]
    end

    resources :trips do
        resources :participants, only: [:index, :create, :destroy]
    end

    resources :trips, only: [:create, :destroy]    ## if i remove this, the create trip does not work

    resources :sessions,   only: [:new, :create, :destroy]
    resources :microposts, only: [:create, :destroy]
    resources :relationships, only: [:create, :destroy]

    root to: 'static_pages#home'

    match '/signup',    to: 'users#new'
    match '/signin',    to: 'sessions#new'
    match '/signout',   to: 'sessions#destroy', via: :delete


    match '/map',       to: 'map#map'

    match '/help',      to: 'static_pages#help'
    match '/about',     to: 'static_pages#about'
    match '/contact',   to: 'static_pages#contact'

    match '/trips',      to: 'trips#alltrips'



    get "proxy" => "proxy#get", :as =>"proxy"




end

app/views/shared/_enrollment.html.erb
<li id="<%= enrollment.id %>">
    <div style="float:left;width:8%;";><%= link_to trip.name, user_trip_path(@user.id, trip.id) %></div>
    <div style="float:left;width:20%;";><%= trip.description %></div>
    <div style="float:left;width:10%;";><%= "%.6f" % trip.center.x %></div>
    <div style="float:left;width:10%;";><%= "%.6f" % trip.center.y %></div>
    <div style="float:left;width:8%;";><%= trip.zoom %></div>
    <div style="clear:both"></div>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-error">
            The form contains <%= pluralize(object.errors.count, "error") %>
        </div>
        <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
    <ol class="microposts">
        <%= render partial: 'shared/feed_item', collection: @feed_items %>
    </ol>
    <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
    <%= link_to gravatar_for(feed_item.user), feed_item.user %>
    <span class="user">
        <%= link_to feed_item.user.name, feed_item.user %>
    </span>
    <span class="content"><%= feed_item.content %></span>
    <span class="timestamp">
        Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
    <% if current_user?(feed_item.user) %>
        <%= link_to "delete", feed_item, method: :delete, data: { confirm: "You sure?" }, title: feed_item.content %>
    <% end %>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
        <%= f.text_area :content, placeholder: "Compose new micropost..." %>
    </div>
    <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
    <% ## These are trips that I have joined and trips that I have created %>


    <% ## Note, the following path is incorrect.  I think I need an ernollments route %>
    <a href="<%= user_enrollments_path(@user) %>">
        <strong id="following" class="stat">
            <%= @user.enrollments.count %>
        </strong>
        trips I have joined
    </a>
    <a href="<%= user_trips_path(@user) %>">
        <strong id="followers" class="stat">
            <%= @user.trips.count %>
        </strong>
        My trips
    </a>
</div>

app/views/shared/_trip.html.erb
<li id="<%= trip.id %>">
    <div style="float:left;width:8%;";><%= link_to trip.name, user_trip_path(@user.id, trip.id) %></div>
    <div style="float:left;width:20%;";><%= trip.description %></div>
    <div style="float:left;width:10%;";><%= "%.6f" % trip.center.x %></div>
    <div style="float:left;width:10%;";><%= "%.6f" % trip.center.y %></div>
    <div style="float:left;width:8%;";><%= trip.zoom %></div>
    <div style="clear:both"></div>
</li>

app/views/shared/_trip_form.html.erb
<%= form_for(@trip) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
        <%= f.text_field :name, placeholder: "Name your trip..." %>
        <%= f.text_area :description, placeholder: "Compose a trip description..." %>
        <%= f.text_field :latitude, placeholder: "Latitude location of center..." %>
        <%= f.text_field :longitude,placeholder: "Longitude location of center..." %>
        <%= f.text_field :zoom, placeholder: "Zoom level..." %>
    </div>
    <%= f.submit "Create trip", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_tripfeed.html.erb
<% if @tripfeed_items.any? %>
    <ol class="microposts">
        <%= render partial: 'shared/tripfeed_item', collection: @tripfeed_items %>
    </ol>
    <%= will_paginate @tripfeed_items %>
<% end %>

app/views/shared/_tripfeed_item.html.erb
<li id="<%= tripfeed_item.id %>">
    <%= link_to gravatar_for(tripfeed_item.user), tripfeed_item.user %>
    <span class="user">
        <%= link_to tripfeed_item.user.name, tripfeed_item.user %>
    </span>
    <span class="content"><%= tripfeed_item.name %></span>
    <span class="timestamp">
        Posted <%= time_ago_in_words(tripfeed_item.created_at) %> ago.
    </span>
    <% if current_user?(tripfeed_item.user) %>
        <%= link_to "delete", tripfeed_item, method: :delete, data: { confirm: "You sure?" }, title: tripfeed_item.name %>
    <% end %>
</li>

app/views/shared/_tripstats.html.erb
<% @user ||= current_user %>
<div class="stats">
    Path to trips joined
        <strong id="following" class="stat">
            X joined
        </strong>
        joined
    
    <a href="<%= user_trips_path(@user) %>">
        <strong id="followers" class="stat">
            <%= @user.trips.count %>
        </strong>
        leading
    </a>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
    <%= gravatar_for current_user, size: 52 %>
</a>
<h1>
    <%= current_user.name %>
</h1>
<span>
    <%= link_to "view my profile", current_user %>
</span>
<span>
    <%= pluralize(current_user.trips.count, "micropost") %>
</span>