config/routes.rb
Olapp::Application.routes.draw do

  # get "users/new"

    resources :users do
        member do
            get :following, :followers
        end
        resources :trips, only: [:index, :create, :destroy]  ## if we remove this, the home page does not work
        resources :enrollments, only: [:index, :create, :destroy]
    end

    resources :trips do
        resources :participants, only: [:index, :create, :destroy]
    end

    resources :trips, only: [:create, :destroy]    ## if i remove this, the create trip does not work

    resources :sessions,   only: [:new, :create, :destroy]
    resources :microposts, only: [:create, :destroy]
    resources :relationships, only: [:create, :destroy]

    root to: 'static_pages#home'

    match '/signup',    to: 'users#new'
    match '/signin',    to: 'sessions#new'
    match '/signout',   to: 'sessions#destroy', via: :delete


    match '/map',       to: 'map#map'

    match '/help',      to: 'static_pages#help'
    match '/about',     to: 'static_pages#about'
    match '/contact',   to: 'static_pages#contact'

    match '/trips',      to: 'trips#alltrips'



    get "proxy" => "proxy#get", :as =>"proxy"




end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.waterpathcanoe.com">CanoeTrek</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "CanoeTrek", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Map", map_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_onecolumn.html.erb
<div id="header">
</div>


<div id="content">
    <%= yield %>
</div>

<div id="footer">
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_twocolumn.html.erb
    <div id="wrapper">
        <div id="content_wrapper">
            <div id="content_inner_wrapper">
                <%= render 'layouts/header' %>
    <div id="right-column">
    </div>
                <%= yield %>
            </div>
        </div>
    </div>
    <div id="footer_wrapper">
        <div id="footer_inner_wrapper">
            <div id="my-footer-content">
                <%= render 'layouts/footer' %>
                <!-- <%= debug(params) if Rails.env.development? %> -->
            </div>
        </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
</head>
<body>
    <%= render 'layouts/header' %>
    <div class="container">
        <% flash.each do |key, value| %>
            <%= content_tag(:div, value, class: "alert alert-#{key}") %>
        <% end %>
        <%= yield %>
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
    </div>
</body>
</html>

app/views/layouts/map_two_column.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= include_gon %>
  <%= stylesheet_link_tag    "manifest_map", :media => "all" %>
  <%= javascript_include_tag "manifest_map" %>
  <%= csrf_meta_tags %>
</head>
<body class="app">


<div id="header">
    <div class="navbar">
        <div class="container">
            <a href="/" id="logo">CanoeTrek</a>
            <nav>
                <ul class="nav pull-right">
                    <li><%= link_to "Home", root_path %></li>
                    <li><%= link_to "Map", map_path %></li>
                    <li><%= link_to "Help", help_path %></li>
                <% if signed_in? %>
                    <li><%= link_to "Users", users_path %></li>
                    <li id="fat-menu" class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Account <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><%= link_to "Profile", current_user %></li>
                            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                            <li class="divider"></li>
                            <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
                        </ul>
                    </li>
                <% else %>
                    <li><%= link_to "Sign in", signin_path %></li>
                <% end %>
                </ul>
            </nav>
        </div>
    </div>
</div>



    <div id="content">
        <div id="middle-container">
            <div id="right-column">Right Column</div>
            <%= yield %>
        </div>
    </div>



<div id="footer">
    This is the footer
    <br />The map footer
</div>

    
</body>
</html>